"""add user addresses, states, phone, ally assignments

Revision ID: 77be71b29544
Revises: 3310eba9b0c5
Create Date: 2026-04-11 22:21:13.432854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77be71b29544'
down_revision = '3310eba9b0c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ally_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ally_id', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.String(length=30), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ally_id'], ['ally.id'], name='fk_uaa_ally_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_uaa_user_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_ally_assignment'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('home_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('home_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('work_address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('work_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('work_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('employee_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('status_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status_notes')
        batch_op.drop_column('status_end_date')
        batch_op.drop_column('status_start_date')
        batch_op.drop_column('employee_status')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('work_longitude')
        batch_op.drop_column('work_latitude')
        batch_op.drop_column('work_address')
        batch_op.drop_column('home_longitude')
        batch_op.drop_column('home_latitude')
        batch_op.drop_column('home_address')

    op.drop_table('user_ally_assignment')
    # ### end Alembic commands ###
